spring.application.name=characters_api

spring.datasource.url=jdbc:postgresql://ep-morning-truth-ady3ohyl-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jqh3B4dUFQNv

spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE